# Generated by Django 5.0.6 on 2024-07-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock_status',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='stock_status',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='popularity',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='stock_status',
            field=models.CharField(default='high', max_length=20),
            preserve_default=False,
        ),
    ]
